/* Generated by Together */

#include <stdlib.h>
#include <string>
#include "CPOI.h"
using namespace std;
#include "CGPSSensor.h"

CGPSSensor::CGPSSensor()
{}

CWaypoint CGPSSensor::getCurrentPosition()
{	string name;
	double latitude,longitude;
	cout<<"GPS Sensor"<<endl;

	cout<<"Enter Latitude : "<<endl;
	cin>>latitude;
	cout<<"Enter Longitude : "<<endl;
	cin>>longitude;

	CWaypoint result("",latitude,longitude);

	return result;
}

