/* Generated by Together */
#include <iostream>
#include <stdlib.h>
#include <string>
#include "CWaypoint.h"

#ifndef CGPSSENSOR_H
#define CGPSSENSOR_H
class CGPSSensor{
public:

    CWaypoint getCurrentPosition();

    CGPSSensor();
};
#endif //CGPSSENSOR_H
