/* Generated by Together */

#include <iostream>
#include <stdlib.h>
#include <string>
#include "CWaypoint.h"
#include "CPOIDataBase.h"

#include "CNavigationSystem.h"
using namespace std;

CNavigationSystem::CNavigationSystem()
{

}

void CNavigationSystem::run()
{m_route.ConnecttoPoiDatabase(& m_PoiDatabase);
	int number,state=0;
	string filename,filename2,mode;
cout<<"helloo"<<endl;
	do
	{cout<<"1-Build Up default route"<<endl;
	 cout<<"2-Print the Route"<<endl;
 	 cout<<"3-Find Next POI for current GPS position"<<endl;
 	 cout<<"4-Please Select Mode"<<endl;
	 cout<<"5-Write route to file"<<endl;
 	 cout<<"6-Read Route from file"<<endl<<endl;
 	cout<<"0-Exit program"<<endl;

 	 cout<<"Give ur desired number"<<endl;
 			cin>>number;
 			state=number;
	switch(state){

		case 0:
			cout<<"good bye"<<endl;
//		number=0;
				break;
		case 1: {enterRoute();
		cout<<"route built"<<endl;
		state=0;


		break;}


		case 2:{printRoute();
		state=0;

		break;}
		case 3:{printDistanceCurPosNextPoi();
		state=0;

		break;}

		case 4:
		{cout<<"I-Indent Format"<<endl;
		 cout<<"C-CVS Format"<<endl;
		 cin>>mode;
		 state=0;
		break;
		}
		case 5:{cout<<"Enter your desired filename with .txt extension"<<endl;
				cin>>filename;
				CIndentCodec hello;
				CCSVCodec hello3;
				if(mode=="C" || mode=="c")
				m_route.writeToFile(filename,hello3);
				else if(mode=="I" || mode=="i")
					m_route.writeToFile(filename,hello);
			state=0;

		break;}
		case 6:{cout<<"Enter your desired filename with .txt extension"<<endl;
				cin>>filename2;
				CIndentCodec hello2;
				CCSVCodec hello4;
				if(mode=="C" || mode=="c")
					m_route.readFromFile(filename2,true,hello4);
					else if(mode=="I" || mode=="i")
					m_route.readFromFile(filename2,true,hello2);

			state=0;

		break;}
	}

	}while(number!=0);

}

void CNavigationSystem::enterRoute()
{
//	CRoute temp;
//	m_route=temp;
CWaypoint Darmstadt("abdullah",49.8667, 8.6500);
m_route.addwaypoint(Darmstadt);
CWaypoint Berlin("Berlin",52.5167,13.3833);
m_route.addwaypoint(Berlin);
CWaypoint Amsterdam("Amsterdam",52.3731, 4.8922);
m_route.addwaypoint(Amsterdam);

m_route.ConnecttoPoiDatabase(& m_PoiDatabase);
//
	m_PoiDatabase.addPoi(club,"H_da Mensa","The Best mensa in the world",10,20);
	m_PoiDatabase.addPoi(restaurant,"Sitte","More Expensive but also good",11,22);
    m_PoiDatabase.addPoi(restaurant,"minhaj","More Expensive but also good",11,22);
    m_PoiDatabase.addPoi(restaurant,"sarosh","More Expensive but also good",11,22);
    m_PoiDatabase.addPoi(restaurant,"usman","More Expensive but also good",11,22);
//
//
    m_route.addPoi("Sitte1");
    m_route.addPoi("H_da Mensa");
    m_route.addPoi("minhaj");
    m_route.addPoi("sarosh1");
    m_route.addPoi("usman");


}

void CNavigationSystem::printRoute()
{
	m_route.print();

}

void CNavigationSystem::printDistanceCurPosNextPoi()
{
	CPOI position;
	CWaypoint wp;
	double result;
		wp=m_GPSSensor.getCurrentPosition();
		result=m_route.getDistanceNextPoi(wp, position);

		cout << "Distance to next POI : " <<result<< endl;


		position.print(2);


}


