/* Generated by Together */

#ifndef CNAVIGATIONSYSTEM_H_
#define CNAVIGATIONSYSTEM_H_
#include <iostream>
#include <stdlib.h>
#include <string>
#include "CWaypoint.h"
#include "CPOIDataBase.h"
#include "CGPSSensor.h"
#include "CRoute.h"
#include "CCSVCodec.h"
using namespace std;

class CNavigationSystem
{
private:
	CGPSSensor m_GPSSensor;
	CRoute m_route;
	CPOIDataBase m_PoiDatabase;
	void enterRoute();
	void printRoute();
	void printDistanceCurPosNextPoi();

public:
	CNavigationSystem();
	void run();

};

#endif /* CNAVIGATIONSYSTEM_H_ */
