/* Generated by Together */

#include <iostream>
#include <stdlib.h>
#include <string>
#include "CWaypoint.h"
#include "CPOIDataBase.h"
#include "CNavigationSystem.h"
#include "CPOI.h"
using namespace std;

CPOIDataBase::CPOIDataBase()
{
//m_noPoi=10;



}

void CPOIDataBase::addPoi(t_poi type, string name, string description,
		double latitude, double longitude)
{
	CPOI obj(type, name, description, latitude, longitude);
	m_POI.insert(pair<string, CPOI>(name,obj));

//	static int i = 0;
//		if(i < m_noPoi)
//		{
//			CPOI obj(type, name, description, latitude, longitude);
//			m_POI[i] = obj;
//			i++;
//		}
//		else
//		{
//			cout << "List is full" << endl;
//		}


}



CPOI* CPOIDataBase::getPointerToPOI(string name)
{

map<string,CPOI>::iterator i;
for(i=m_POI.begin();i!=m_POI.end();i++)
{
	if(i->second.getName()==name)
		return  &i->second;
		}

	//
//int i;
//for(i=0;i<m_noPoi;i++)
//	{
//	if(m_POI[i].getName()==name)
//
//		return & m_POI[i];
//
//	}
return NULL;
}





