/* Generated by Together */
#ifndef CPOIDATABASE_H
#define CPOIDATABASE_H

#include <iostream>
#include <stdlib.h>
#include <string>
#include "CPOI.h"
#include <map>
using namespace std;


class CPOIDataBase {
private:
//	CPOI m_POI[10];
//	int m_noPoi;
map<string, CPOI> m_POI;
public:

CPOIDataBase();
    void addPoi(t_poi type, string name, string description, double latitude,
			double longitude);
    CPOI* getPointerToPOI(string name);

};
#endif //CPOIDATABASE_H
