/* Generated by Together */
#include <iostream>
#include <stdlib.h>
#include <string>
#include "CPOI.h"

using namespace std;


CPOI::CPOI(){}
CPOI::CPOI(t_poi type, string name="", string description="", double latitude=0,
		double longitude=0)
{
m_type=type;
m_description=description;
set(name,latitude,longitude);
//cout<<"hello"<<endl;


}

string CPOI::getDescription() const
{
	return m_description;
}

t_poi CPOI::getType() const
{
	return m_type;
}

void CPOI::Print()
{
	switch (m_type){

		case restaurant:
		{
			cout<<"Of type Restaurant : "<<m_description<<endl<<" Name: ";
			CWaypoint::print(1);
			break;
		}


		case club:
			{
				cout<<"Of type Club :"<<m_description<<endl<<" Name: ";
				CWaypoint::print(1);

				break;
			}

		case mall:
			{
				cout<<"Of type Restaurant : "<<m_description<<endl<<" Name: ";
				CWaypoint::print(1);

				break;
			}

		case Nill:
			break;

		default:
			cout<<"Please Enter the Correct Point of Interest "<<endl;
			break;


		}





}


